services:
  mongodb:
    container_name: mongodb-componentes-eletronicos
    image: mongo:8
    volumes:
      - vol-mongodb:/data/db
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
  api:
    container_name: componentes-eletronicos
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=production
      - DB_URL=mongodb://mongodb:27017/componentes-eletronicos
    env_file:
      - .env
    depends_on:
      - mongodb

volumes:
  vol-mongodb: