services:
    mongodb:
        container_name: mongodb-componentes-eletronicos
        image: mongo:8
        volumes:
            - vol-mongodb:/data/db
        command: mongod --quiet --logpath /dev/null
        ports:
            - 27017:27017
    api:
        container_name: componentes-eletronicos
        build: .
        ports:
            - "${PORT}:${PORT}"
        environment:
            - NODE_ENV=production
            - DB_URL=mongodb://mongodb:27017/componentes-eletronicos
        env_file:
            - .env
        depends_on:
            - mongodb
    minio:
        image: minio/minio:latest
        container_name: minio
        ports:
            - "${MINIO_PORT}:${MINIO_PORT}"
            - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
        volumes:
            - ./minio-data:/data
        environment:
            - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
            - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
            - MINIO_BROWSER_REDIRECT_URL=http://localhost:${MINIO_CONSOLE_PORT}

        command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
volumes:
    vol-mongodb: